/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main_Form;

import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author HP
 */
public class FormPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form Form
     */
    JPanel bottomPanel;
    public FormPanel(JPanel bottomPanel) {
        this.bottomPanel=bottomPanel;
        initComponents();
    }
    private File selectedPhotoFile;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderbuttonGroup1 = new javax.swing.ButtonGroup();
        titlejLabel1 = new javax.swing.JLabel();
        firstnamejLabel1 = new javax.swing.JLabel();
        firstnamejTextField1 = new javax.swing.JTextField();
        lastnamejLabel1 = new javax.swing.JLabel();
        lastnamejTextField1 = new javax.swing.JTextField();
        agejLabel1 = new javax.swing.JLabel();
        agejTextField1 = new javax.swing.JTextField();
        emailjLabel1 = new javax.swing.JLabel();
        emailjTextField1 = new javax.swing.JTextField();
        messagejLabel1 = new javax.swing.JLabel();
        ptypejLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        genderjLabel1 = new javax.swing.JLabel();
        malejRadioButton1 = new javax.swing.JRadioButton();
        femalejRadioButton1 = new javax.swing.JRadioButton();
        othersjRadioButton1 = new javax.swing.JRadioButton();
        photojLabel1 = new javax.swing.JLabel();
        uploadjButton1 = new javax.swing.JButton();
        datejLabel1 = new javax.swing.JLabel();
        submitjButton1 = new javax.swing.JButton();
        jDatePicker1 = new org.jdatepicker.JDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagejTextField1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(400, 400));

        titlejLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        titlejLabel1.setText("Patient Details");

        firstnamejLabel1.setText("FirstName");

        lastnamejLabel1.setText("LastName");

        agejLabel1.setText("Age");

        emailjLabel1.setText("Email");

        messagejLabel1.setText("Message");

        ptypejLabel1.setText("Patient Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Patient", "Emergency", "Scheduled Patient", "Unscheduled Patient" }));

        genderjLabel1.setText("Gender");

        GenderbuttonGroup1.add(malejRadioButton1);
        malejRadioButton1.setText("Male");

        GenderbuttonGroup1.add(femalejRadioButton1);
        femalejRadioButton1.setText("Female");

        GenderbuttonGroup1.add(othersjRadioButton1);
        othersjRadioButton1.setText("Others");

        photojLabel1.setText("Choose Photo");

        uploadjButton1.setText("Upload");
        uploadjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadjButton1ActionPerformed(evt);
            }
        });

        datejLabel1.setText("Date");

        submitjButton1.setText("Submit");
        submitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton1ActionPerformed(evt);
            }
        });

        messagejTextField1.setColumns(20);
        messagejTextField1.setRows(5);
        jScrollPane1.setViewportView(messagejTextField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastnamejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ptypejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(othersjRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(femalejRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agejTextField1)
                    .addComponent(lastnamejTextField1)
                    .addComponent(firstnamejTextField1)
                    .addComponent(emailjTextField1)
                    .addComponent(malejRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uploadjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(submitjButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlejLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titlejLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamejTextField1)
                    .addComponent(firstnamejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamejTextField1)
                    .addComponent(lastnamejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(agejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjTextField1)
                    .addComponent(emailjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptypejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(messagejLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderjLabel1)
                    .addComponent(malejRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femalejRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(othersjRadioButton1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datejLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(photojLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uploadjButton1)))
                .addGap(18, 18, 18)
                .addComponent(submitjButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

         
    private void uploadjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadjButton1ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedPhotoFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Photo selected successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_uploadjButton1ActionPerformed

    
    
     private boolean validateInputs() {
    // Validation for First Name
    if (firstnamejTextField1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the First Name.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validation for Last Name
    if (lastnamejTextField1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the Last Name.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validation for Age (should be an integer value)
    try {
        int age = Integer.parseInt(agejTextField1.getText());
        if (age < 0 || agejTextField1.getText().length()>2) {
            throw new NumberFormatException();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid integer for Age.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validation for Email (basic email format check)
    String email = emailjTextField1.getText().trim();
    if (!email.matches("[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}")) {
        JOptionPane.showMessageDialog(this, "Please enter a valid Email address.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
     // Validation for Message
    if (messagejTextField1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Message.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
     // Validation for Date
    if (jDatePicker1.getModel().getValue() == null) {
        JOptionPane.showMessageDialog(this, "Please select a date.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    // Validation for Photo selected
    if (selectedPhotoFile == null) {
        JOptionPane.showMessageDialog(this, "Please select a photo.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
}
    
    
    
    
    
    
    
    private void submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton1ActionPerformed
        // TODO add your handling code here:
        // Validate inputs before proceeding
    if (validateInputs()) {
        // If inputs are valid, proceed with further actions
        // For example, you can save the data to a database or perform other operations
        // You can also display a success message here
        String date = ""+jDatePicker1.getModel().getDay()+"-"+jDatePicker1.getModel().getMonth()+ " - "+jDatePicker1.getModel().getYear();
        String gender = "";
        if(malejRadioButton1.isSelected()){
            gender = "Male";
        }else if(femalejRadioButton1.isSelected()){
            gender = "Female";
        }else{
            gender = "Others";
        }
        
        JOptionPane.showMessageDialog(this, "Form submitted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        Patient p=new Patient(firstnamejTextField1.getText(), lastnamejTextField1.getText(), Integer.parseInt(agejTextField1.getText()), 
                emailjTextField1.getText(), messagejTextField1.getText(), jComboBox1.getSelectedItem().toString(), gender, date, selectedPhotoFile);
        
        ViewPanel view = new ViewPanel(p);
        bottomPanel.add(view);
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        cl.next(bottomPanel);
        
        
    }
    }//GEN-LAST:event_submitjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderbuttonGroup1;
    private javax.swing.JLabel agejLabel1;
    private javax.swing.JTextField agejTextField1;
    private javax.swing.JLabel datejLabel1;
    private javax.swing.JLabel emailjLabel1;
    private javax.swing.JTextField emailjTextField1;
    private javax.swing.JRadioButton femalejRadioButton1;
    private javax.swing.JLabel firstnamejLabel1;
    private javax.swing.JTextField firstnamejTextField1;
    private javax.swing.JLabel genderjLabel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastnamejLabel1;
    private javax.swing.JTextField lastnamejTextField1;
    private javax.swing.JRadioButton malejRadioButton1;
    private javax.swing.JLabel messagejLabel1;
    private javax.swing.JTextArea messagejTextField1;
    private javax.swing.JRadioButton othersjRadioButton1;
    private javax.swing.JLabel photojLabel1;
    private javax.swing.JLabel ptypejLabel1;
    private javax.swing.JButton submitjButton1;
    private javax.swing.JLabel titlejLabel1;
    private javax.swing.JButton uploadjButton1;
    // End of variables declaration//GEN-END:variables
}
