/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main_Form;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author HP
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    JPanel bottomPanel;
    Patient patient;
    public ViewPanel(Patient patient) {
        this.patient = patient;
        initComponents();
        setValues();
    }
    
    void setValues(){
        
         // jTextFieldFirstname.setText(user.getFirstname());
         /* firstnamejTextField1.setText(patient.getFirstName());
          lastnamejTextField1.setText(patient.getLastName());
          agejTextField1.setText(Integer.toString(patient.getAge()));
          emailjTextField1.setText(patient.getEmail());
          messagejTextField1.setText(patient.getMessage());*/
         
        firstnamejLabel1.setText(patient.getFirstName());
        lastnamejLabel1.setText(patient.getLastName());
        agejLabel1.setText(Integer.toString(patient.getAge()));
        emailjLabel1.setText(patient.getEmail());
        messagejTextArea1.setText(patient.getMessage());
        ptypejLabel1.setText(patient.getPatienttype());
        genderjLabel1.setText(patient.getGender());
        datejLabel1.setText(patient.getDate());
       // photojLabel1.setIcon(new ImageIcon(new ImageIcon(patient.getPhoto().getAbsolutePath()).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
        ImageIcon profilePhoto = new ImageIcon(new ImageIcon(patient.getPhoto().toString()).getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH));
        photojLabel1.setIcon(profilePhoto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel1 = new javax.swing.JLabel();
        datejLabel1 = new javax.swing.JLabel();
        ptypejLabel1 = new javax.swing.JLabel();
        firstnamejLabel1 = new javax.swing.JLabel();
        genderjLabel1 = new javax.swing.JLabel();
        lastnamejLabel1 = new javax.swing.JLabel();
        agejLabel1 = new javax.swing.JLabel();
        photojLabel1 = new javax.swing.JLabel();
        emailjLabel1 = new javax.swing.JLabel();
        fnamejLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagejTextArea1 = new javax.swing.JTextArea();
        lnamejLabel1 = new javax.swing.JLabel();
        agejLabel2 = new javax.swing.JLabel();
        messagejLabel3 = new javax.swing.JLabel();
        ptypejLabel2 = new javax.swing.JLabel();
        genderjLabel2 = new javax.swing.JLabel();
        datejLabel2 = new javax.swing.JLabel();
        emailjLabel2 = new javax.swing.JLabel();
        photojLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));

        titlejLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titlejLabel1.setText("Patient  Details");
        titlejLabel1.setMaximumSize(new java.awt.Dimension(85, 17));
        titlejLabel1.setMinimumSize(new java.awt.Dimension(85, 17));

        datejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        ptypejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        firstnamejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firstnamejLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        genderjLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lastnamejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        agejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        photojLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        emailjLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        fnamejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fnamejLabel1.setText("First Name :");

        messagejTextArea1.setEditable(false);
        messagejTextArea1.setColumns(20);
        messagejTextArea1.setRows(5);
        jScrollPane1.setViewportView(messagejTextArea1);

        lnamejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lnamejLabel1.setText("Last Name :");

        agejLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agejLabel2.setText("Age :");

        messagejLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        messagejLabel3.setText("Message :");

        ptypejLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ptypejLabel2.setText("Patient Type :");

        genderjLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderjLabel2.setText("Gender :");

        datejLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        datejLabel2.setText("Date :");

        emailjLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailjLabel2.setText("Email :");

        photojLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        photojLabel2.setText("Photo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ptypejLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagejLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agejLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnamejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fnamejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datejLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photojLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(photojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailjLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agejLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastnamejLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamejLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderjLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ptypejLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(datejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamejLabel1)
                    .addComponent(fnamejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamejLabel1)
                    .addComponent(lnamejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejLabel1)
                    .addComponent(agejLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailjLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptypejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptypejLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderjLabel1)
                            .addComponent(genderjLabel2)))
                    .addComponent(messagejLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datejLabel2)
                    .addComponent(datejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photojLabel2)
                    .addComponent(photojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agejLabel1;
    private javax.swing.JLabel agejLabel2;
    private javax.swing.JLabel datejLabel1;
    private javax.swing.JLabel datejLabel2;
    private javax.swing.JLabel emailjLabel1;
    private javax.swing.JLabel emailjLabel2;
    private javax.swing.JLabel firstnamejLabel1;
    private javax.swing.JLabel fnamejLabel1;
    private javax.swing.JLabel genderjLabel1;
    private javax.swing.JLabel genderjLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastnamejLabel1;
    private javax.swing.JLabel lnamejLabel1;
    private javax.swing.JLabel messagejLabel3;
    private javax.swing.JTextArea messagejTextArea1;
    private javax.swing.JLabel photojLabel1;
    private javax.swing.JLabel photojLabel2;
    private javax.swing.JLabel ptypejLabel1;
    private javax.swing.JLabel ptypejLabel2;
    private javax.swing.JLabel titlejLabel1;
    // End of variables declaration//GEN-END:variables
}
